# Generated by Django 3.0.3 on 2020-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadFF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ff_upload', models.FileField(help_text='Файл ogg, mp3', upload_to='files_ff', verbose_name='Файл')),
                ('name_of_file_ff', models.CharField(max_length=30, verbose_name='код')),
            ],
        ),
    ]
