# Generated by Django 3.1.5 on 2021-01-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrie_name', models.CharField(help_text='Страна', max_length=30, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': '01 Страны',
            },
        ),
        migrations.CreateModel(
            name='InventoryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=40, unique=True, verbose_name='Инвентарный номер')),
            ],
            options={
                'verbose_name': 'Инвентарный номер',
                'verbose_name_plural': 'Инвентарные номера',
            },
        ),
        migrations.CreateModel(
            name='Naspunkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naspunkt_name', models.CharField(help_text='Населённый пункт', max_length=30, verbose_name='Населённый пункт')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': '04 Населенные пункты',
            },
        ),
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oblast_name', models.CharField(help_text='Область', max_length=30, verbose_name='Область')),
                ('oblast', models.ForeignKey(default='Российская Федерация', on_delete=django.db.models.deletion.DO_NOTHING, to='base.countries', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': '02 Области',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organisation', models.CharField(max_length=30, verbose_name='Аббревиатура')),
                ('full_name_organisation', models.CharField(max_length=120, verbose_name='Полное наименование')),
                ('email_organisation', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('about_organisation', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_researcher', models.CharField(help_text='Фамилия Имя Отчество', max_length=50, verbose_name='ФИО')),
                ('email_researcher', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('about_researcher', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Исследователь',
                'verbose_name_plural': 'Исследователи',
            },
        ),
        migrations.CreateModel(
            name='SeansOfRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_seans_of_record', models.DateField(verbose_name='Дата сеанса записи')),
                ('place_of_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.naspunkt', verbose_name='Место записи')),
            ],
            options={
                'verbose_name': 'Сеанс записи',
                'verbose_name_plural': 'Сеансы записи',
            },
        ),
        migrations.CreateModel(
            name='Rajon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rajon_name', models.CharField(help_text='Район', max_length=30, verbose_name='Район')),
                ('rajon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.oblast', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': '03 Районы',
            },
        ),
        migrations.AddField(
            model_name='naspunkt',
            name='naspunkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.rajon', verbose_name='Район'),
        ),
        migrations.CreateModel(
            name='Informant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='Фамилия Имя Отчество указывать полностью', max_length=50, verbose_name='ФИО')),
                ('date_of_birth', models.IntegerField(blank=True, help_text='Указывать только год рождения. Точную дату при необходимости добавить в "Дополнительно"', null=True, verbose_name='Год рождения')),
                ('img_informant', models.ImageField(blank=True, null=True, upload_to='informants/', verbose_name='Фотография исполнителя')),
                ('info_informant', models.TextField(help_text='Здесь можно добавить такие сведения как: девичья фамилия, место рождения, год переезда, точная дата рождения, контактная информация', verbose_name='Дополнительная информация')),
                ('data_seans_of_record_inf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.seansofrecord')),
                ('place_of_residence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.naspunkt', verbose_name='Место проживания')),
            ],
            options={
                'verbose_name': 'Информант',
                'verbose_name_plural': 'Информанты',
            },
        ),
        migrations.CreateModel(
            name='HddMediaDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdd_drive', models.CharField(max_length=30, verbose_name='Производитель ЖД')),
                ('hdd_drive_capacity', models.CharField(max_length=5, verbose_name='Объем диска в гигобайтах')),
                ('inventory_number_hdd', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='base.inventorynumber', verbose_name='Инвентарный номер')),
            ],
            options={
                'verbose_name': 'Жесткий диск (HDD)',
                'verbose_name_plural': 'Жесткие диски (HDD)',
            },
        ),
        migrations.CreateModel(
            name='Expeditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_data_expedition', models.DateField(verbose_name='Дата начала экспедиции')),
                ('end_data_expedition', models.DateField(blank=True, default='00.00.0000', null=True, verbose_name='Дата окончания экспедиции')),
                ('organisation_expedition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.organisation', verbose_name='Организация')),
                ('researcher_expedtion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.researcher', verbose_name='Руководитель экспедиции')),
            ],
            options={
                'verbose_name': 'Экспедиция',
                'verbose_name_plural': 'Экспедиции',
            },
        ),
        migrations.CreateModel(
            name='DigitalMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_digitl_media', models.CharField(default='CRF20201213_34_A', max_length=45, unique=True, verbose_name='ID цифровой записи')),
                ('fileupl', models.FileField(upload_to='audio/', verbose_name='Аудиофайл')),
                ('file_description', models.TextField(default='00:00:00 Русского \n00:00:30 Конец', max_length=600, verbose_name='Описание и тайминг')),
                ('place_hdd_drive', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='base.hddmediadrive', verbose_name='На каком HDD хранится')),
                ('seans', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.seansofrecord')),
            ],
            options={
                'verbose_name': 'Цифровой медиа файл',
                'verbose_name_plural': 'Цифровые медиа файлы',
            },
        ),
    ]
