# Generated by Django 2.2.3 on 2019-07-26 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrie_name', models.CharField(help_text='Страна', max_length=30, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oblast_name', models.CharField(help_text='Область', max_length=30, verbose_name='Область')),
                ('oblast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Rajon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rajon_name', models.CharField(help_text='Район', max_length=30, verbose_name='Район')),
                ('rajon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Oblast')),
            ],
        ),
        migrations.CreateModel(
            name='Naspunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naspunkt_name', models.CharField(help_text='Населённый пункт', max_length=30, verbose_name='Населённый пункт')),
                ('naspunkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Rajon')),
            ],
        ),
    ]
