# Generated by Django 2.2.3 on 2019-07-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrie_name', models.CharField(help_text='Страна', max_length=30, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': '01 Страны',
            },
        ),
        migrations.CreateModel(
            name='InventoryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=40, unique=True, verbose_name='Инвентарный номер')),
            ],
            options={
                'verbose_name': 'Инвентарный номер',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type_a', models.CharField(help_text='аудиокассета, бобина, видеокассета VHS', max_length=30, verbose_name='Тип аналогового носителя')),
                ('manufacturer', models.CharField(blank=True, max_length=30, verbose_name='Производитель')),
                ('additional_note', models.TextField(blank=True, help_text='время звучания, метраж, для какого типа воспроизводящего устройства и прочее', verbose_name='Дополнительные сведения')),
            ],
            options={
                'verbose_name': 'Тип носителя',
                'verbose_name_plural': 'Типы носителей',
            },
        ),
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oblast_name', models.CharField(help_text='Область', max_length=30, verbose_name='Область')),
                ('oblast', models.ForeignKey(default='Российская Федерация', on_delete=django.db.models.deletion.DO_NOTHING, to='base.Countries', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': '02 Области',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organisation', models.CharField(max_length=30, verbose_name='Аббревиатура')),
                ('full_name_organisation', models.CharField(max_length=60, verbose_name='Полное наименование')),
                ('email_organisation', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('about_organisation', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_researcher', models.CharField(help_text='Фамилия Имя Отчество', max_length=50, verbose_name='ФИО')),
                ('email_researcher', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('about_researcher', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Исследователь',
                'verbose_name_plural': 'Исследователи',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_place', models.CharField(max_length=30, unique=True, verbose_name='Номер места хранения')),
            ],
            options={
                'verbose_name': 'Номер места хранения',
                'verbose_name_plural': 'Номер места хранения',
            },
        ),
        migrations.CreateModel(
            name='Rajon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rajon_name', models.CharField(help_text='Район', max_length=30, verbose_name='Район')),
                ('rajon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Oblast', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': '03 Районы',
            },
        ),
        migrations.CreateModel(
            name='Naspunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naspunkt_name', models.CharField(help_text='Населённый пункт', max_length=30, verbose_name='Населённый пункт')),
                ('naspunkt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Rajon', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': '04 Населенные пункты',
            },
        ),
        migrations.CreateModel(
            name='Informant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='Фамилия Имя Отчество', max_length=50, verbose_name='ФИО')),
                ('maiden_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Девичья фамилия')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('date_move', models.IntegerField(blank=True, verbose_name='Год переезда')),
                ('place_of_birth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.Naspunk', verbose_name='Место рождения')),
                ('place_of_residence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Naspunk', verbose_name='Место проживания')),
            ],
            options={
                'verbose_name': 'Информант',
                'verbose_name_plural': 'Информанты',
            },
        ),
        migrations.CreateModel(
            name='FizNositel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number_fzn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.InventoryNumber', verbose_name='Инвентарный номер')),
                ('media_type_fzn', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.MediaType', verbose_name='Тип носителя')),
                ('storaje_location_fzn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.StorageLocation', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'Физический носитель',
                'verbose_name_plural': 'Физические носители',
            },
        ),
        migrations.CreateModel(
            name='Expeditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_data_expedition', models.DateField(verbose_name='Дата начала экспедиции')),
                ('end_data_expedition', models.DateField(blank=True, default='00.00.0000', null=True, verbose_name='Дата окончания экспедиции')),
                ('organisation_expedition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Organisation', verbose_name='Организация')),
                ('researcher_expedtion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Researcher', verbose_name='Руководитель экспедиции')),
            ],
            options={
                'verbose_name': 'Экспедиция',
                'verbose_name_plural': 'Экспедиции',
            },
        ),
    ]
