# Generated by Django 2.2.3 on 2019-07-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryFizNositel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_fiz_nositel', models.ImageField(upload_to='gallery_fiz_nositel', verbose_name='Фотография обложек и вложенных описей')),
            ],
        ),
        migrations.AlterModelOptions(
            name='inventorynumber',
            options={'verbose_name': 'Инвентарный номер', 'verbose_name_plural': 'Инвентарные номера'},
        ),
        migrations.AlterField(
            model_name='organisation',
            name='full_name_organisation',
            field=models.CharField(max_length=120, verbose_name='Полное наименование'),
        ),
        migrations.AddField(
            model_name='fiznositel',
            name='img_fiz_nos_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.GalleryFizNositel', verbose_name='изображение'),
        ),
    ]
