# Generated by Django 2.2.3 on 2019-08-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalmedia',
            options={'verbose_name': 'Цифровой медиа файл', 'verbose_name_plural': 'Цифровые медиа файлы'},
        ),
        migrations.AlterModelOptions(
            name='hddmediadrive',
            options={'verbose_name': 'Жесткий диск (HDD)', 'verbose_name_plural': 'Жесткие диски (HDD)'},
        ),
        migrations.AlterModelOptions(
            name='mediatype',
            options={'verbose_name': 'Тип аналового носителя', 'verbose_name_plural': 'Типы аналоговых носителей'},
        ),
        migrations.AddField(
            model_name='digitalmedia',
            name='media_file',
            field=models.FileField(default='no', upload_to='digitalmedia/%Y/%m/', verbose_name='Загрузить звуковой файл'),
        ),
        migrations.AlterField(
            model_name='digitalmedia',
            name='path_of_place',
            field=models.CharField(default='/', max_length=300, verbose_name='Путь до папки на жестком диске'),
        ),
        migrations.AlterField(
            model_name='digitalmedia',
            name='place_hdd_drive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='base.HddMediaDrive', verbose_name='На каком HDD хранится'),
        ),
        migrations.AlterField(
            model_name='timingdigitalmedia',
            name='number_of_temestamp',
            field=models.IntegerField(default='0', unique=True, verbose_name='Порядковый номер'),
        ),
    ]
