# Generated by Django 2.2.3 on 2019-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organisation', models.CharField(max_length=30, verbose_name='Аббревиатура')),
                ('full_name_organisation', models.CharField(max_length=60, verbose_name='Полное наименование')),
                ('email_organisation', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('about_organisation', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
