# Generated by Django 2.2.3 on 2019-07-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type_a', models.CharField(help_text='аудиокассета, бобина, видеокассета VHS', max_length=30, verbose_name='Тип аналогового носителя')),
                ('manufacturer', models.CharField(blank=True, max_length=30, verbose_name='Производитель')),
                ('additional_note', models.TextField(blank=True, help_text='время звучания, оценка ветхости и прочее', verbose_name='Дополнительные сведения')),
            ],
            options={
                'verbose_name': 'Тип носителя',
                'verbose_name_plural': 'Типы носителей',
            },
        ),
    ]
