# Generated by Django 2.2.3 on 2019-07-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190730_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiznositel',
            name='img_fiz_nos_key',
        ),
        migrations.AddField(
            model_name='galleryfiznositel',
            name='img_fiz_nos_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.FizNositel', verbose_name='изображение'),
        ),
    ]
