# Generated by Django 3.0.3 on 2020-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190827_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalmedia',
            name='path_of_place',
        ),
        migrations.AlterField(
            model_name='digitalmedia',
            name='id_of_digitl_media',
            field=models.AutoField(default='000000', primary_key=True, serialize=False, unique=None, verbose_name='ID цифровой записи'),
        ),
        migrations.AlterField(
            model_name='timingdigitalmedia',
            name='number_of_temestamp',
            field=models.IntegerField(default='0', unique=None, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='timingdigitalmedia',
            name='time_stamp',
            field=models.TimeField(default='00:00:00', unique=None, verbose_name='час:минута:секунда'),
        ),
    ]
