# Generated by Django 3.1.5 on 2021-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210126_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informant',
            name='info_informant',
            field=models.TextField(blank=True, help_text='Здесь можно добавить такие сведения как: девичья фамилия, место рождения, год переезда, точная дата рождения, дата смерти, контактная информация', verbose_name='Дополнительная информация'),
        ),
    ]
