# Generated by Django 2.2.3 on 2019-07-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190730_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryfiznositel',
            options={'verbose_name': 'Фото носителя', 'verbose_name_plural': 'Фотографии носителей'},
        ),
        migrations.AddField(
            model_name='fiznositel',
            name='fzn_doc',
            field=models.FileField(blank=True, null=True, upload_to='fzn_doc/%Y/%m/%d/', verbose_name='файл с описанием содержимого'),
        ),
        migrations.AddField(
            model_name='fiznositel',
            name='fzn_txt',
            field=models.TextField(blank=True, help_text='Ветхость, скорость записи (для бобин), и прочие примечания', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fiznositel',
            name='inventory_number_fzn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='base.InventoryNumber', verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='galleryfiznositel',
            name='img_fiz_nositel',
            field=models.ImageField(upload_to='gallery_fiz_nositel/%Y/%m/%d/', verbose_name='Фотография обложек и вложенных описей'),
        ),
        migrations.AlterField(
            model_name='inventorynumber',
            name='inventory_number',
            field=models.CharField(max_length=40, verbose_name='Инвентарный номер'),
        ),
    ]
