# Generated by Django 3.1.5 on 2021-01-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210126_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informant',
            name='data_seans_of_record_inf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.seansofrecord'),
        ),
    ]
