# Generated by Django 2.2.3 on 2019-07-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_mediatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=40, unique=True, verbose_name='Инвентарный номер')),
            ],
            options={
                'verbose_name': 'Инвентарный номер',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_place', models.CharField(max_length=30, unique=True, verbose_name='Номер места хранения')),
            ],
            options={
                'verbose_name': 'Номер места хранения',
                'verbose_name_plural': 'Номер места хранения',
            },
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='additional_note',
            field=models.TextField(blank=True, help_text='время звучания, метраж, для какого типа воспроизводящего устройства и прочее', verbose_name='Дополнительные сведения'),
        ),
        migrations.AlterField(
            model_name='oblast',
            name='oblast',
            field=models.ForeignKey(default='Российская Федерация', on_delete=django.db.models.deletion.DO_NOTHING, to='base.Countries', verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='FizNositel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number_fzn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.InventoryNumber', verbose_name='Инвентарный номер')),
                ('storaje_location_fzn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.StorageLocation', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'Физический носитель',
                'verbose_name_plural': 'Физические носители',
            },
        ),
        migrations.CreateModel(
            name='Expeditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_data_expedition', models.DateField(verbose_name='Дата начала экспедиции')),
                ('end_data_expedition', models.DateField(blank=True, verbose_name='Дата окончания экспедиции')),
                ('organisation_expedition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Organisation', verbose_name='Организация')),
                ('researcher_expedtion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Researcher', verbose_name='Руководитель экспедиции')),
            ],
            options={
                'verbose_name': 'Экспедиция',
                'verbose_name_plural': 'Экспедиции',
            },
        ),
    ]
