# Generated by Django 2.2.3 on 2019-07-31 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190731_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiznositel',
            name='storaje_location_fzn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.StorageLocation', unique=True, verbose_name='Место хранения'),
        ),
        migrations.AlterField(
            model_name='inventorynumber',
            name='inventory_number',
            field=models.CharField(max_length=40, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
