# Generated by Django 3.1.5 on 2021-01-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210126_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informant',
            name='data_seans_of_record_inf',
        ),
        migrations.AddField(
            model_name='seansofrecord',
            name='informant_of_seanse',
            field=models.ManyToManyField(to='base.Informant'),
        ),
    ]
