# Generated by Django 2.2.3 on 2019-07-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190731_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiznositel',
            name='storaje_location_fzn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.StorageLocation', verbose_name='Место хранения'),
        ),
    ]
