# Generated by Django 3.1.5 on 2021-01-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210126_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditions',
            name='seanses_of_expedition',
            field=models.ManyToManyField(blank=True, to='base.SeansOfRecord', verbose_name='Сеансы записи'),
        ),
        migrations.AlterField(
            model_name='seansofrecord',
            name='informant_of_seanse',
            field=models.ManyToManyField(to='base.Informant', verbose_name='Информанты сеанса'),
        ),
    ]
