# Generated by Django 2.2.3 on 2019-08-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190731_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='informant',
            name='date_move',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год переезда'),
        ),
    ]
